const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={day:1,time:12,energy:10,money:600,confidence:0,fitness:0,discipline:0,nutrition:0,groom:0,recovery:0,acting:0,hindi:0,dance:0,selftape:0,karate:0,counts:{gym:0,nutrition:0,groom:0,recovery:0},daily:{},fatigue:0};
let old={};try{old=JSON.parse(localStorage.getItem('pabh-save')||'null')||{}}catch(e){}
let state={...defaults,...old,counts:{...defaults.counts,...(old.counts||{})},daily:old.daily||{}};
if(typeof state.dance==='object') state.dance=0;
const goals={gym:3,nutrition:5,groom:2,recovery:3};
const labels={gym:'Gym',nutrition:'Nutrition',groom:'Style & Grooming',recovery:'Recovery & Movement'};
const icons={gym:'🏋️',nutrition:'🥗',groom:'✂️',recovery:'🌙'};
const stages=[
 {n:1,title:'BUILD YOURSELF',threshold:0,desc:'Build enough proof, routine and self-belief to walk into acting training.',unlock:'Acting Training'},
 {n:2,title:'FIND YOUR VOICE',threshold:100,desc:'Train the actor. Build craft, voice, Hindi and movement.',unlock:'Camera Work'},
 {n:3,title:'FACE THE CAMERA',threshold:220,desc:'Headshots, scene work and self-tapes become part of the journey.',unlock:'Auditions'},
 {n:4,title:'PUT YOURSELF OUT THERE',threshold:400,desc:'Audition, network and earn real experience instead of preparing forever.',unlock:'India Readiness'},
 {n:5,title:'INDIA READY',threshold:650,desc:'Bring craft, confidence, fitness, portfolio and money together.',unlock:'Mumbai'}
];
const activities={
 gym:{title:'GYM',heading:'SHOW UP.',story:'You don’t need the perfect program today. You need evidence that you can keep a promise to yourself.',image:'assets/gym.webp',choices:[
   {name:'Foundation Strength',meta:'2h · −2 Energy',desc:'A steady full-body session. Leave with something in the tank.',time:2,energy:2,money:0,confidence:10,fitness:5,discipline:3,result:'You trained without trying to prove anything. That matters.'},
   {name:'Cardio + Mobility',meta:'1h · −1 Energy',desc:'Lower pressure. Build stamina and keep the streak alive.',time:1,energy:1,money:0,confidence:6,fitness:3,discipline:2,result:'You kept momentum alive. A smaller win still changes the story.'},
   {name:'Push Hard',meta:'3h · −4 Energy',desc:'A bigger session with a recovery cost tomorrow.',time:3,energy:4,money:0,confidence:8,fitness:8,discipline:2,fatigue:2,result:'Big session. You feel accomplished — and you’ll feel it tomorrow.'}
 ]},
 nutrition:{title:'NUTRITION',heading:'FUEL THE VERSION YOU WANT.',story:'Training is only part of the rebuild. What you choose after the workout decides whether today compounds.',image:'assets/home-approved.png',choices:[
   {name:'Stick to the Plan',meta:'−$12',desc:'A filling, protein-focused meal that supports the goal.',time:0,energy:0,money:12,confidence:8,nutrition:5,discipline:2,result:'You chose the long-term version of yourself over the impulse.'},
   {name:'Cook at Home',meta:'1h · −$7',desc:'Cheaper and controlled, but it costs some of your day.',time:1,energy:0,money:7,confidence:6,nutrition:4,discipline:3,result:'Not glamorous, but sustainable. You saved money and stayed aligned.'},
   {name:'Convenient Healthy Option',meta:'−$20',desc:'Spend more to make the right choice easier today.',time:0,energy:0,money:20,confidence:7,nutrition:4,discipline:1,result:'You removed friction instead of relying on willpower.'}
 ]},
 groom:{title:'STYLE & GROOMING',heading:'START SEEING YOURSELF DIFFERENTLY.',story:'Confidence is also built in the mirror. This isn’t about pretending you’re finished — it’s about showing yourself you matter now.',image:'assets/home-approved.png',choices:[
   {name:'Simple Reset',meta:'1h · −$15',desc:'Hair, beard/skin care, clothes laid out properly.',time:1,energy:0,money:15,confidence:6,groom:5,result:'Small details changed how you carried yourself for the rest of the day.'},
   {name:'Wardrobe Upgrade',meta:'2h · −$80',desc:'Buy one piece that fits your current body well instead of waiting.',time:2,energy:1,money:80,confidence:10,groom:9,result:'You stopped postponing looking good until some future version of you exists.'},
   {name:'No-Spend Style Session',meta:'1h',desc:'Build two outfits from what you already own and photograph them.',time:1,energy:0,money:0,confidence:5,groom:4,discipline:2,result:'You made progress without spending anything. Useful proof.'}
 ]},
 recovery:{title:'RECOVERY & MOVEMENT',heading:'DON’T BURN OUT THE STORY.',story:'The rebuild only works if tomorrow still has energy. Recovery is part of discipline, not the opposite of it.',image:'assets/home-approved.png',choices:[
   {name:'Early Night',meta:'End day · +2 Energy tomorrow',desc:'Protect sleep and let the routine settle.',time:0,energy:0,money:0,confidence:5,recovery:6,discipline:2,endDay:true,result:'You chose tomorrow on purpose.'},
   {name:'Easy Walk',meta:'1h · −1 Energy',desc:'Clear your head and get some movement without another hard session.',time:1,energy:1,money:0,confidence:5,recovery:4,fitness:2,result:'You moved without turning everything into punishment.'},
   {name:'Quiet Reset',meta:'1h',desc:'Stretch, shower, tidy the room, get tomorrow ready.',time:1,energy:0,money:0,confidence:4,recovery:5,discipline:2,result:'Your environment feels less chaotic. Tomorrow now has a runway.'}
 ]}
};
let currentActivity='gym';
const dkey=k=>`${state.day}:${k}`;
function save(){localStorage.setItem('pabh-save',JSON.stringify(state))}
function doneToday(k){return !!state.daily[dkey(k)]}
function foundationsDone(){return Object.keys(goals).filter(k=>(state.counts[k]||0)>=goals[k]).length}
function stage1Complete(){return state.confidence>=100&&foundationsDone()===4}
function currentStage(){if(stage1Complete()) return state.confidence>=650?5:state.confidence>=400?4:state.confidence>=220?3:2;return 1}
function stagePct(){if(currentStage()===1){let xp=Math.min(1,state.confidence/100),f=foundationsDone()/4;return Math.round(((xp*.65)+(f*.35))*100)}let s=currentStage(),next=stages[s]||null,cur=stages[s-1];if(!next)return 100;return Math.round(Math.max(0,Math.min(1,(state.confidence-cur.threshold)/(next.threshold-cur.threshold)))*100)}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));window.scrollTo(0,0);render()}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),1700)}
function modal(title,text,kicker='RESULT'){$('#modalKicker').textContent=kicker;$('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#modal').classList.add('show')}
function nextFoundation(){for(const k of ['gym','nutrition','groom','recovery']) if((state.counts[k]||0)<goals[k]&&!doneToday(k)) return k;for(const k of ['gym','nutrition','groom','recovery']) if(!doneToday(k)) return k;return null}
function recommendation(){if(stage1Complete())return {icon:'🎭',title:'Acting Training Unlocked',text:'You built the foundation. The next chapter is learning the craft.',label:'VIEW JOURNEY',go:'journey'};let k=nextFoundation();if(k)return {icon:icons[k],title:k==='gym'?'Go to the Gym':labels[k],text:{gym:'Start with action. Build physical momentum and self-trust.',nutrition:'Make the next meal support the person you are becoming.',groom:'Invest in how you carry yourself now — not later.',recovery:'Protect the routine so tomorrow still works.'}[k],label:'CONTINUE STORY →',activity:k};return {icon:'🌙',title:'Today is complete',text:'You’ve made every Stage 1 decision available today. Let the progress compound.',label:'END DAY',end:true}}
function openActivity(k){if(doneToday(k)){toast('You already made this decision today');return}currentActivity=k;let a=activities[k];$('#activityTitle').textContent=a.title;$('#eventHeading').textContent=a.heading;$('#eventStory').textContent=a.story;$('#activityImage').src=a.image;$('#activityImage').alt=a.title;renderChoices();go('activity')}
function renderChoices(){let a=activities[currentActivity];$('#choiceList').innerHTML=a.choices.map((c,i)=>`<button class="choiceCard" data-choice="${i}"><div><small>${String(i+1).padStart(2,'0')}</small><b>${c.name}</b><em>${c.meta}</em></div><p>${c.desc}</p><span>Confidence +${c.confidence} →</span></button>`).join('');$$('[data-choice]').forEach(b=>b.onclick=()=>makeChoice(+b.dataset.choice))}
function makeChoice(i){let k=currentActivity,a=activities[k],c=a.choices[i];if(doneToday(k))return toast('Already done today');if(state.time<c.time)return toast('Not enough time left today');if(state.energy<c.energy)return toast('Not enough energy');if(state.money<c.money)return toast('Not enough money');state.time-=c.time;state.energy-=c.energy;state.money-=c.money;state.confidence+=c.confidence||0;state.fitness=Math.min(100,state.fitness+(c.fitness||0));state.discipline=Math.min(100,state.discipline+(c.discipline||0));state.nutrition=Math.min(100,state.nutrition+(c.nutrition||0));state.groom=Math.min(100,state.groom+(c.groom||0));state.recovery=Math.min(100,state.recovery+(c.recovery||0));state.fatigue=Math.max(state.fatigue,c.fatigue||0);state.counts[k]=(state.counts[k]||0)+1;state.daily[dkey(k)]=true;let unlocked=stage1Complete();save();render();modal(unlocked?'ACTING TRAINING UNLOCKED':c.name.toUpperCase(),`${c.result}\n\nConfidence +${c.confidence}. ${stage1Complete()?'Stage 1 is complete. You are ready to begin training as an actor.':`${100-Math.min(100,state.confidence)} Confidence to the next unlock.`}`,unlocked?'NEW STAGE':'TODAY');if(c.endDay)setTimeout(()=>{},0)}
function endDay(){state.day++;state.time=12;state.energy=Math.max(6,10-state.fatigue);state.fatigue=0;save();render();modal('DAY '+state.day,'The stats reset. The proof you built does not. Keep going.','NEW DAY')}
function renderHome(){if(!$('#homeConfidence'))return;$('#homeConfidence').textContent=state.confidence;$('#homeConfidenceBar').style.width=Math.min(100,state.confidence)+'%';$('#homeStagePct').textContent=stagePct()+'%';$('#unlockRequirement').textContent=stage1Complete()?'Unlocked — your next chapter is ready.':`${foundationsDone()}/4 foundations complete · ${Math.min(100,state.confidence)}/100 Confidence`;let r=recommendation();$('#homeNextIcon').textContent=r.icon;$('#homeNextTitle').textContent=r.title;$('#homeNextText').textContent=r.text;$('#homeNextAction').textContent=r.label;$('#homeNextAction').onclick=()=>r.activity?openActivity(r.activity):r.go?go(r.go):r.end?endDay():null;$('#homeFoundations').innerHTML=Object.keys(goals).map(k=>`<button class="foundationPill ${(state.counts[k]||0)>=goals[k]?'complete':''}" data-home-activity="${k}" ${doneToday(k)?'disabled':''}><span>${icons[k]}</span><b>${labels[k]}</b><small>${Math.min(state.counts[k]||0,goals[k])}/${goals[k]}</small></button>`).join('');$$('[data-home-activity]').forEach(b=>b.onclick=()=>openActivity(b.dataset.homeActivity));$('#endDayHome').textContent=Object.values(activities).some((_,i)=>!doneToday(Object.keys(activities)[i]))?'END DAY EARLY':'END DAY · REST & RESET'}
function renderJourney(){if(!$('#stagePath'))return;let s=currentStage();$('#stagePath').innerHTML=stages.map(x=>{let status=x.n<s?'complete':x.n===s?'active':'locked';let detail=x.n===1?`${foundationsDone()}/4 foundations · ${Math.min(100,state.confidence)}/100 Confidence`:x.n===2?'Acting craft · Hindi · Movement':x.n===3?'Headshots · Scenes · Self-tapes':x.n===4?'Auditions · Network · Credits':'Craft · Fitness · Portfolio · Money';return `<article class="pathStage ${status}"><div class="node">${status==='complete'?'✓':x.n}</div><div class="pathCopy"><small>STAGE ${x.n} · ${status==='active'?'CURRENT':status==='complete'?'COMPLETE':'LOCKED'}</small><b>${x.title}</b><p>${x.desc}</p><em>${detail}</em><strong>${status==='locked'?'🔒 '+x.unlock:status==='active'?'NEXT UNLOCK: '+x.unlock:'UNLOCKED'}</strong></div></article>`}).join('')}
function renderYou(){if(!$('#stats'))return;$('#youArc').textContent=stages[currentStage()-1].title;$('#youConfidence').textContent=state.confidence;$('#youConfidenceBar').style.width=Math.min(100,state.confidence)+'%';let stats=[['Fitness',state.fitness],['Discipline',state.discipline],['Nutrition',state.nutrition],['Style',state.groom],['Recovery',state.recovery],['Acting',state.acting],['Hindi',state.hindi],['Dance',state.dance]];$('#stats').innerHTML=stats.map(([n,v])=>`<div class="statTile"><span>${n}</span><b>${v}</b><div class="bar"><i style="width:${v}%"></i></div></div>`).join('');$('#foundationGoals').innerHTML=Object.keys(goals).map(k=>`<div class="goalRow ${(state.counts[k]||0)>=goals[k]?'done':''}"><span>${icons[k]} ${labels[k]}</span><b>${Math.min(state.counts[k]||0,goals[k])}/${goals[k]}</b></div>`).join('')}
function render(){ $$('[data-day]').forEach(x=>x.textContent=state.day);$$('[data-time]').forEach(x=>x.textContent=state.time);$$('[data-energy]').forEach(x=>x.textContent=state.energy);$$('[data-money]').forEach(x=>x.textContent='$'+state.money);renderHome();renderJourney();renderYou() }
$('#begin').onclick=()=>{$('#splash').classList.remove('active');$('#game').classList.add('active');go('home')};$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#endDayHome').onclick=endDay;$('#modalClose').onclick=()=>{$('#modal').classList.remove('show');go('home')};document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});render();
