const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={day:1,time:12,energy:10,money:600,fitness:0,discipline:0,acting:0,selftape:0,hindi:0,groom:0,karate:0,dance:0,gymDay:0,sets:{}};
let old=JSON.parse(localStorage.getItem('pabh-save')||'null')||{};
let state={...defaults,...old,discipline:old.discipline||0,dance:typeof old.dance==='object'?Math.max(0,...Object.values(old.dance)):old.dance||0,sets:old.sets||{}};
const exercises=[['Chest Press',3,12],['Lat Pulldown',3,12],['Leg Press',3,12],['Seated Row',3,12]];
const key=(i)=>`${state.day}-${i}`;
function save(){localStorage.setItem('pabh-save',JSON.stringify(state))}
function completed(i){return state.sets[key(i)]||0}
function totalSets(){return exercises.reduce((n,_,i)=>n+completed(i),0)}
function readiness(){return Math.min(100,Math.round((state.fitness+state.discipline+state.acting+state.selftape+state.hindi+state.groom+state.karate+state.dance)/8))}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),1500)}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));window.scrollTo(0,0);render()}
function render(){ $$('[data-day]').forEach(x=>x.textContent=state.day);$$('[data-time]').forEach(x=>x.textContent=state.time);$$('[data-energy]').forEach(x=>x.textContent=state.energy);$$('[data-money]').forEach(x=>x.textContent='$'+state.money);renderGym();renderDevelop() }
function renderGym(){let list=$('#exerciseList');if(!list)return;list.innerHTML=exercises.map((e,i)=>{let c=completed(i);return `<article class="exercise ${c===e[1]?'done':''}"><div class="exTop"><span>${String(i+1).padStart(2,'0')}</span><div><b>${e[0]}</b><small>${e[1]} SETS × ${e[2]} REPS</small></div><strong>${c}/${e[1]}</strong></div><div class="pips">${Array.from({length:e[1]},(_,j)=>`<i class="${j<c?'on':''}"></i>`).join('')}</div><button data-set="${i}" ${c>=e[1]||state.gymDay===state.day?'disabled':''}>${c>=e[1]?'COMPLETE':'COMPLETE SET '+(c+1)}</button></article>`}).join('');$$('[data-set]').forEach(b=>b.onclick=()=>doSet(+b.dataset.set));let t=totalSets();$('#setCount').textContent=`${t}/12 SETS`;let f=$('#finishWorkout');f.classList.toggle('locked',t<12||state.gymDay===state.day);f.disabled=t<12||state.gymDay===state.day}
function doSet(i){if(state.gymDay===state.day)return toast('Workout already completed today');if(totalSets()===0){if(state.time<2||state.energy<2)return toast('You need 2 hours and 2 energy');state.time-=2;state.energy-=2}let max=exercises[i][1];if(completed(i)<max){state.sets[key(i)]=completed(i)+1;state.discipline=Math.min(100,state.discipline+1);save();render();toast(`${exercises[i][0]} · set ${completed(i)} complete`)}}
function finish(){if(totalSets()<12||state.gymDay===state.day)return;state.gymDay=state.day;state.fitness=Math.min(100,state.fitness+5);state.discipline=Math.min(100,state.discipline+3);save();render();$('#modalTitle').textContent='WORKOUT COMPLETE';$('#modalText').textContent='Fitness +5 · Discipline +3. Day 1 is no longer just intention — you trained.';$('#modal').classList.add('show')}
function renderDevelop(){if(!$('#stats'))return;let r=readiness();$('#readyPct').textContent=r+'%';$('#readyBar').style.width=r+'%';let stats=[['Fitness',state.fitness],['Discipline',state.discipline],['Acting',state.acting],['Self-Tape',state.selftape],['Hindi',state.hindi],['Style & Grooming',state.groom],['GKR Karate',state.karate],['Dance',state.dance]];$('#stats').innerHTML=stats.map(([n,v])=>`<div class="stat"><span>${n}</span><b>${v}/100</b><div><i style="width:${v}%"></i></div></div>`).join('')}
function begin(){ $('#splash').classList.remove('active');$('#game').classList.add('active');go('home') }
$('#begin').onclick=begin;$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#finishWorkout').onclick=finish;$('#modalClose').onclick=()=>$('#modal').classList.remove('show');document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});render();
