const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state=JSON.parse(localStorage.getItem('pabh-save')||'null')||{day:1,time:12,energy:10,money:600,fitness:0,acting:0,selftape:0,hindi:0,groom:0,karate:0,dance:{classical:0,garba:0,bhangra:0,salsa:0,bachata:0,swing:0},credits:0};
const costs={gym:[2,2,0],acting:[3,2,80],selftape:[2,2,0],dance:[2,2,35],karate:[2,2,0],hindi:[1,1,0],work:[4,3,-300],groom:[1,0,50]};
const danceNames=Object.keys(state.dance);
function readiness(){let d=Math.max(...Object.values(state.dance));return Math.min(100,Math.round((state.fitness+state.acting+state.selftape+state.hindi+state.groom+state.karate+d)/7));}
function stage(){return Math.min(4,Math.floor(state.fitness/20));}
function save(){localStorage.setItem('pabh-save',JSON.stringify(state))}
function render(){ $('#day').textContent=state.day;$('#time').textContent=state.time;$('#energy').textContent=state.energy;$('#money').textContent='$'+state.money;let r=readiness();$('#ready').textContent=r;$('#indiaPct').textContent=r+'%';$('#readinessBar').style.width=r+'%';let st=stage(), names=['STARTING','EARLY CHANGE','LEANER','FIT','SCREEN READY'];$('#scene').className='scene stage'+st;$('#physiqueName').textContent=names[st];$('#roomName').textContent=state.selftape>45?'Professional self-tape setup':state.selftape>20?'Developing self-tape setup':'Basic self-tape corner';
let stats=[['Acting',state.acting],['Fitness',state.fitness],['Self-Tape / Audition',state.selftape],['Hindi',state.hindi],['Grooming & Style',state.groom],['GKR Karate',state.karate]];$('#stats').innerHTML=stats.map(x=>`<div class='stat'><b>${x[0]}</b><small>${x[1]}/100</small><div class='mini'><i style='width:${x[1]}%'></i></div></div>`).join('');
let ports=[['📸','Headshots',state.groom>=15],['🎥','Audition Videos',state.selftape>=10],['🎬','Starter Showreel',state.selftape>=25&&state.acting>=20],['📄','Acting Résumé',state.acting>=25],['⭐','Screen Credits',state.credits>0],['🏆','Professional Reel',state.selftape>=60&&state.acting>=55]];$('#portfolio').innerHTML=ports.map(p=>`<div class='port ${p[2]?'':'locked'}'><i>${p[0]}</i><b>${p[1]}</b><small>${p[2]?'UNLOCKED':'LOCKED'}</small></div>`).join('');
let skills=[['🎭','Acting',state.acting],['🥋','GKR Karate',state.karate],['🗣️','Hindi',state.hindi],...danceNames.map(n=>['💃',n[0].toUpperCase()+n.slice(1),state.dance[n]])];$('#skillList').innerHTML=skills.map(s=>`<div class='skill'><span class='ico'>${s[0]}</span><div class='copy'><b>${s[1]}</b><div class='mini'><i style='width:${s[2]}%'></i></div></div><span class='lvl'>${label(s[2])}</span></div>`).join('');
let checks=[['Acting training',state.acting],['Portfolio / self-tapes',state.selftape],['Physical readiness',state.fitness],['Hindi',state.hindi],['Dance',Math.max(...Object.values(state.dance))],['GKR Karate',state.karate],['Style / grooming',state.groom]];$('#indiaChecks').innerHTML=checks.map(c=>`<div class='check'><span>${c[0]}</span><span>${label(c[1])}</span></div>`).join('');$('#moveIndia').classList.toggle('locked',state.day<30);}
function label(v){return v>=80?'STANDOUT':v>=60?'STRONG':v>=40?'COMPETENT':v>=20?'DEVELOPING':v>0?'BEGINNER':'UNTRAINED'}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1400)}
function act(type){let [t,e,m]=costs[type];if(state.time<t||state.energy<e||state.money<m){toast('Not enough time, energy or money');return}state.time-=t;state.energy-=e;state.money-=m;let before=stage();if(type==='gym'){state.fitness=Math.min(100,state.fitness+4);toast('Fitness +4')}if(type==='acting'){state.acting=Math.min(100,state.acting+5);toast('Acting +5')}if(type==='selftape'){state.selftape=Math.min(100,state.selftape+4);state.acting=Math.min(100,state.acting+1);toast('Self-tape +4')}if(type==='dance'){let n=danceNames[Math.floor((state.day-1)/3)%danceNames.length];state.dance[n]=Math.min(100,state.dance[n]+5);toast(`${n[0].toUpperCase()+n.slice(1)} +5`)}if(type==='karate'){state.karate=Math.min(100,state.karate+4);toast('GKR Karate +4')}if(type==='hindi'){state.hindi=Math.min(100,state.hindi+3);toast('Hindi +3')}if(type==='work'){toast('India fund +$300')}if(type==='groom'){state.groom=Math.min(100,state.groom+5);toast('Style +5')}if(stage()>before)modal('PHYSICAL UPGRADE','Your training is showing. Your character has visibly changed.');save();render()}
function modal(t,p){$('#levelTitle').textContent=t;$('#levelText').textContent=p;$('#levelup').classList.add('show')}
function beginGame(){const splash=$('#splash'),game=$('#game');if(!splash||!game)return;splash.classList.remove('active');game.classList.add('active');render();window.scrollTo(0,0)}
const beginBtn=$('#begin');if(beginBtn){beginBtn.addEventListener('click',beginGame);beginBtn.addEventListener('touchend',e=>{e.preventDefault();beginGame()},{passive:false});}$$('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));$('#endDay').onclick=()=>{state.day++;state.time=12;state.energy=10;if(state.day%7===0&&state.acting>=15){state.credits++;modal('AUDITION OPPORTUNITY',state.credits===1?'Your preparation has earned your first small screen credit. Your résumé is no longer empty.':'Another credit added to your acting résumé.')}save();render();scrollTo(0,0)};$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$$('.tab').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active');scrollTo(0,0)});$('#closeModal').onclick=()=>$('#levelup').classList.remove('show');$('#moveIndia').onclick=()=>state.day<30?toast('Reach Day 30 before making the move'):modal('MUMBAI AWAITS',`You are ${readiness()}% India Ready. In the full game, this begins Chapter 2 — and your preparation determines which doors open first.`);document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});render();
